# Generated by Django 3.0.4 on 2020-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpingorg',
            name='organisation_ptr',
        ),
        migrations.DeleteModel(
            name='AskingOrg',
        ),
        migrations.DeleteModel(
            name='HelpingOrg',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
